theme: jekyll-theme-cayman
title: 「オンライン心理学実験・調査入門：誰でも簡単,Googleフォームとlab.jsで作れる!」サポートサイト
description: 「オンライン心理学実験・調査入門：誰でも簡単,Googleフォームとlab.jsで作れる!」で章ごとに紹介したlab.jsプログラムのソースファイルとデモ，便利ツールなどを提供しています。ソースファイルはJSON形式です。ソースファイルはクリックするとダウンロードできます。なお，デモを利用したデータ収集はご遠慮ください。